### ISSUE TITLE
sample application

### ISSUE THREAD

**Issue by josephjp** [talos-code/mylar#8]
Hi,
I was looking for a sample application using mylar.
The following link https://github.com/gliesesoftware/mylar-encchat
doesnt seem to work. I found the link in https://atmospherejs.com/mylar/platform.

Is there a sample application which I could look at....

Thanks and Best Regards
Joseph

**Comment by ramijarrar** [comment]
In general, we are not really maintaining these packages for now so unless you feel comfortable enough to figure out from examples @ http://css.csail.mit.edu/mylar/ then you are probably not going to be able to build anything with it.

Worth noting that there seems to be some recent development on this: 

http://people.eecs.berkeley.edu/~raluca/verena.pdf
